id: I85400801
legacy_id: P004294
ocr_import_info:
  bdrc_scan_id: W1KG21953
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T21:22:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T12:50:56.545119+00:00'
last_modified: 2022-08-31 20:51:05.332587
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG21953
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG21953
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་མཁྱེན་ཆོས་འབྱུང་གནས་ཀྱི་གསུང་དགེ་འདུན་ཉི་ཤུའི་རྣམ་གཞག
  author: གུང་རུ་ཆོས་ཀྱི་འབྱུང་གནས།
statistics:
  ocr_word_mean_confidence_index: 0.7607423346390603
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1KG21969:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG21969
      total_pages: 146
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG21969.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7607423346390603
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
